export const VERSION = "0.8.0";
export const SAVE_VERSION = 8;
export const SAVE_KEY = "woodcutter_save";
export const TILE_W = 64;
export const TILE_H = 32;

export const CHANGELOG = [
  {
    ver: "0.8.0",
    items: [
      "Offline progress: 50% efficiency for up to 8h (Timber Network: 100% for up to 24h), with a Welcome Back summary",
      "Background tabs now catch up instead of pausing",
      "Fixed: boss trees now actually appear on the map and can be defeated",
      "Fixed: Ascension perks (Amber tab) now apply their effects; Golden Mutation and Ancient Hunter implemented",
      "Fixed: Eternal Wisdom, Infinite Growth, Auto-Seller, Tree Scanner and Double Strike now work",
      "Fixed: contracts track progress and expire; merchants sell at the market, planters tend stumps",
      "Fixed: importing a save from the title screen",
      "Fixed: workers chasing invisible trees after reload or zone switch",
      "Saves are smaller, kept in a backup slot, and written when the tab is hidden",
      "Sharp rendering on high-DPI screens, zoom (wheel / pinch), redrawn trees, lit night scenes",
      "Frame-rate independent simulation (fixed 20Hz step)",
      "Sound effects (toggle in More → Settings)",
      "Installable offline PWA with a real service worker",
    ],
  },
  {
    ver: "0.7.0",
    items: [
      "Epoch system: 3rd prestige layer above Era",
      "Epoch Perks: 8 permanent abilities (Eternal Wisdom, Cosmic Axe, Time Warp, Infinite Growth, Star Forge, Dimensional Rift, Soul Harvest, Void Touch)",
      "Endless Mode via Infinite Growth perk",
      "8 new upgrades: Log Multiplier, Gold Amplifier, Critical Force, Tree Scanner, Double Strike, Fertile Soil, Auto-Seller, Lucky Drops",
      "25 new achievements including Extinction Event, Billionaire, Trillionaire, Cosmic Being, Reality Bender",
      "Enhanced critical hit system with Void Touch (5x damage)",
      "Lucky Drops for bonus resources on tree chops",
      "Soul Harvest for passive amber gain",
      "Support for over 50 total achievements",
    ],
  },
  {
    ver: "0.6.0",
    items: [
      "Ascension perk tree with branching skill paths",
      "Rare golden and ancient tree mutations",
      "Boss trees with massive HP and big rewards",
      "Prestige cosmetics (axe styles, unlockable)",
      "Trade routes between zones for passive income",
      "Market demand system with fluctuating prices",
      "Contracts board with timed long-term goals",
      "PWA support for offline play and mobile install",
    ],
  },
  {
    ver: "0.5.0",
    items: [
      "Animated tree chopping with rotation fall and particles",
      "Floating damage numbers showing actual damage dealt",
      "Enhanced seasonal system: Spring, Summer, Autumn, Winter with visual effects",
      "Weather system: rain, snow, falling leaves with seasonal effects",
      "Building sprites placed on isometric map",
      "Auto-sell lumberjacks (Merchant workers)",
      "Auto-plant lumberjacks (Planter workers)",
      "Worker types with distinct appearances on map",
      "Luxury goods crafting: Furniture + Charcoal → Luxury Goods",
      "Seasonal gameplay: Spring regrow boost, Autumn leaf drops, Winter bonus sales",
      "Enhanced achievements for new content",
    ],
  },
  {
    ver: "0.4.0",
    items: [
      "Massive progression overhaul",
      "Era system: second prestige layer",
      "Amber: prestige currency earned from seasons",
      "Amber Shop: 10 permanent perks",
      "Quest system: 3 rotating missions",
      "Random events",
      "Tree HP scaling with season number",
    ],
  },
  {
    ver: "0.3.0",
    items: [
      "Versioned saves",
      "Export/import base64",
      "Balance pass",
      "Stats tab",
      "Title screen",
      "Mobile touch",
      "Hotkeys",
    ],
  },
  {
    ver: "0.2.0",
    items: [
      "Day/night cycle",
      "Leaf particles",
      "Tech tree",
      "Processing chains",
      "4 biome zones",
      "Named workers",
      "15 achievements",
      "Offline progress",
    ],
  },
  { ver: "0.1.0", items: ["Initial release"] },
];
export const GRID = 12;
export const BIOMES = [
  { name: "Green Forest", emoji: "🌲", g1: "#2a5a1a", g2: "#276118", tw: [55, 30, 10, 4, 1, 0], cost: 0 },
  { name: "Misty Swamp", emoji: "🌿", g1: "#1a4a3a", g2: "#1a4232", tw: [15, 35, 30, 15, 5, 0], cost: 5000 },
  { name: "Mountain Ridge", emoji: "🏔️", g1: "#3a3a2a", g2: "#333328", tw: [5, 15, 30, 30, 15, 5], cost: 25000 },
  { name: "Enchanted Grove", emoji: "✨", g1: "#2a2a4a", g2: "#252548", tw: [2, 8, 15, 30, 35, 10], cost: 120000 },
  { name: "Frozen Tundra", emoji: "❄️", g1: "#3a4a5a", g2: "#354858", tw: [0, 5, 10, 25, 40, 20], cost: 500000 },
];
export const TREE_TYPES = [
  { name: "Pine", c: "#2d6b3f", tr: "#5a3a1a", hp: 8, y: 1, rg: 10 },
  { name: "Oak", c: "#3a7d32", tr: "#6b4423", hp: 25, y: 4, rg: 15 },
  { name: "Mahogany", c: "#1e5a3a", tr: "#4a2a12", hp: 80, y: 14, rg: 22 },
  { name: "Ironwood", c: "#2a4a3a", tr: "#3a2a18", hp: 250, y: 50, rg: 32 },
  { name: "Heartwood", c: "#4a2d6b", tr: "#2a1a3a", hp: 800, y: 180, rg: 45 },
  { name: "Worldtree", c: "#6a4a1a", tr: "#3a2a0a", hp: 3000, y: 600, rg: 60 },
];
export const WEATHER_SEASONS = [
  { name: "Spring", icon: "🌸", regrowMul: 1.5, treeMul: 1, goldMul: 1, duration: 90 },
  { name: "Summer", icon: "☀️", regrowMul: 1, treeMul: 1, goldMul: 1, duration: 90 },
  { name: "Autumn", icon: "🍂", regrowMul: 0.8, treeMul: 1, goldMul: 1, duration: 90 },
  { name: "Winter", icon: "❄️", regrowMul: 0.5, treeMul: 1, goldMul: 1.2, duration: 90 },
];
export const WORKER_TYPES = [
  { type: "chopper", name: "Chopper", icon: "🪓" },
  { type: "merchant", name: "Merchant", icon: "🛒" },
  { type: "planter", name: "Planter", icon: "🌱" },
];
export const BUILDINGS = [
  { name: "Sawmill", icon: "🏭", pos: { gx: 0.5, gy: 0.5 }, color: "#8a6a4a" },
  { name: "Market", icon: "🏪", pos: { gx: 0.5, gy: GRID - 0.5 }, color: "#8a7a4a" },
  { name: "Nursery", icon: "🌱", pos: { gx: GRID - 0.5, gy: 0.5 }, color: "#6a8a4a" },
  { name: "Kiln", icon: "🔥", pos: { gx: GRID - 0.5, gy: GRID - 0.5 }, color: "#9a5a3a" },
  { name: "Workshop", icon: "🪑", pos: { gx: 1.5, gy: GRID - 1.5 }, color: "#8a5a3a" },
  { name: "Dock", icon: "🚢", pos: { gx: GRID - 1.5, gy: 1.5 }, color: "#5a7a9a" },
];
export const UPGRADES = {
  axe: { name: "Better Axe", icon: "🪓", desc: "+1 chop power", base: 10, mul: 1.5, max: 100, sec: "tools" },
  autoChop: { name: "Auto-Chopper", icon: "⚙️", desc: "Auto-chops/sec", base: 40, mul: 1.45, max: 50, sec: "tools" },
  sawmill: { name: "Sawmill", icon: "🏭", desc: "Logs→Planks auto", base: 150, mul: 1.7, max: 30, sec: "buildings" },
  market: { name: "Market", icon: "🏪", desc: "Auto-sell planks", base: 400, mul: 1.8, max: 25, sec: "buildings" },
  replant: {
    name: "Tree Nursery",
    icon: "🌱",
    desc: "Faster regrowth",
    base: 100,
    mul: 1.6,
    max: 30,
    sec: "buildings",
  },
  enchant: { name: "Enchant Axe", icon: "✨", desc: "+5% crit (2x logs)", base: 600, mul: 2, max: 15, sec: "magic" },
  explore: {
    name: "Forest Scout",
    icon: "🗺️",
    desc: "Unlock rarer trees",
    base: 2000,
    mul: 2.5,
    max: 6,
    sec: "exploration",
  },
  merchant: {
    name: "Hire Merchant",
    icon: "🛒",
    desc: "Auto-sell worker",
    base: 800,
    mul: 1.65,
    max: 20,
    sec: "buildings",
  },
  planter: {
    name: "Hire Planter",
    icon: "🌱",
    desc: "Regrow boost worker",
    base: 600,
    mul: 1.7,
    max: 15,
    sec: "buildings",
  },
  logMulti: {
    name: "Log Multiplier",
    icon: "📦",
    desc: "All log yield +20%",
    base: 500,
    mul: 1.8,
    max: 25,
    sec: "tools",
  },
  goldMulti: {
    name: "Gold Amplifier",
    icon: "💎",
    desc: "All gold income +15%",
    base: 800,
    mul: 1.9,
    max: 20,
    sec: "tools",
  },
  critDmg: {
    name: "Critical Force",
    icon: "⚡",
    desc: "Crit damage +50%",
    base: 1000,
    mul: 2.2,
    max: 10,
    sec: "magic",
  },
  treeScanner: {
    name: "Tree Scanner",
    icon: "🔍",
    desc: "Reveal tree HP & yield",
    base: 300,
    mul: 1.5,
    max: 1,
    sec: "exploration",
  },
  doubleChop: {
    name: "Double Strike",
    icon: "⚔️",
    desc: "Chance to chop twice",
    base: 1500,
    mul: 2.0,
    max: 10,
    sec: "magic",
  },
  regrowBoost: {
    name: "Fertile Soil",
    icon: "🌍",
    desc: "Regrow speed +25%",
    base: 200,
    mul: 1.6,
    max: 20,
    sec: "buildings",
  },
  autoSell: {
    name: "Auto-Seller",
    icon: "🤖",
    desc: "Sells 10% of logs every 5s per level",
    base: 5000,
    mul: 2.0,
    max: 10,
    sec: "buildings",
  },
  luckyDrop: {
    name: "Lucky Drops",
    icon: "🎲",
    desc: "+2% chance bonus drop",
    base: 750,
    mul: 1.8,
    max: 15,
    sec: "magic",
  },
};
export const TECH_TREE = {
  charcoalKiln: { name: "Charcoal Kiln", icon: "🔥", desc: "Logs → Charcoal", cost: 800, req: [] },
  deepRoots: { name: "Deep Roots", icon: "🌳", desc: "Tree yield +50%", cost: 2000, req: ["charcoalKiln"] },
  furnWorkshop: {
    name: "Furniture Workshop",
    icon: "🪑",
    desc: "Planks+Charcoal → Furn",
    cost: 3500,
    req: ["charcoalKiln"],
  },
  druidPact: { name: "Druid Pact", icon: "🧙", desc: "5% instant regrow", cost: 6000, req: ["deepRoots"] },
  magicSap: { name: "Magic Sap", icon: "🧪", desc: "Crit +15%", cost: 8000, req: ["deepRoots"] },
  exportDock: { name: "Export Dock", icon: "🚢", desc: "Auto-sell furniture", cost: 12000, req: ["furnWorkshop"] },
  lumberEmpire: {
    name: "Lumber Empire",
    icon: "👑",
    desc: "All income x2",
    cost: 50000,
    req: ["exportDock", "magicSap"],
  },
  goldenAxe: { name: "Golden Axe", icon: "🏆", desc: "Chop power x3", cost: 120000, req: ["lumberEmpire"] },
  ancientKnow: {
    name: "Ancient Knowledge",
    icon: "📜",
    desc: "Workers chop 2x faster",
    cost: 200000,
    req: ["goldenAxe"],
  },
  worldTreeSeed: {
    name: "Worldtree Seed",
    icon: "🌍",
    desc: "Worldtrees can spawn",
    cost: 400000,
    req: ["ancientKnow"],
  },
  timberNetwork: {
    name: "Timber Network",
    icon: "🌐",
    desc: "Offline progress at 100% for up to 24h",
    cost: 300000,
    req: ["lumberEmpire"],
  },
  eternityForge: {
    name: "Eternity Forge",
    icon: "♾️",
    desc: "Amber gain x2",
    cost: 750000,
    req: ["worldTreeSeed", "timberNetwork"],
  },
  artisanGuild: {
    name: "Artisan Guild",
    icon: "🎨",
    desc: "Furniture→Luxury Goods",
    cost: 100000,
    req: ["furnWorkshop"],
  },
};
export const AMBER_SHOP = [
  { id: "headStart", name: "Head Start", icon: "🚀", desc: "Start seasons with 500 gold", cost: 3, max: 5 },
  { id: "keenEdge", name: "Keen Edge", icon: "🗡️", desc: "+5 starting chop power per level", cost: 2, max: 10 },
  { id: "bornLeader", name: "Born Leader", icon: "👑", desc: "Keep 1 extra worker per season reset", cost: 5, max: 5 },
  { id: "quickStudy", name: "Quick Study", icon: "📚", desc: "Tech costs -10% per level", cost: 4, max: 5 },
  { id: "natureBond", name: "Nature's Bond", icon: "🌿", desc: "Regrow speed +20% per level", cost: 3, max: 5 },
  { id: "goldenTouch", name: "Golden Touch", icon: "✨", desc: "Gold income +15% per level", cost: 4, max: 10 },
  { id: "deepPockets", name: "Deep Pockets", icon: "💰", desc: "Start with 1 free sawmill level", cost: 6, max: 3 },
  { id: "luckCharm", name: "Luck Charm", icon: "🍀", desc: "+3% crit chance per level", cost: 5, max: 5 },
  { id: "zoneMemory", name: "Zone Memory", icon: "🗺️", desc: "Keep 1 unlocked zone per season", cost: 8, max: 4 },
  { id: "amberMagnet", name: "Amber Magnet", icon: "🔶", desc: "+1 bonus amber per season", cost: 10, max: 3 },
];
export const EPOCH_PERKS = [
  { id: "eternalWisdom", name: "Eternal Wisdom", icon: "📖", desc: "All tech costs halved", cost: 5 },
  { id: "cosmicAxe", name: "Cosmic Axe", icon: "🪓", desc: "Base chop power x10", cost: 8 },
  { id: "timeWarp", name: "Time Warp", icon: "⏰", desc: "All production 2x speed", cost: 10 },
  {
    id: "infiniteGrowth",
    name: "Infinite Growth",
    icon: "♾️",
    desc: "Removes ALL upgrade caps (endless mode)",
    cost: 15,
  },
  { id: "starForge", name: "Star Forge", icon: "⭐", desc: "Amber gain x5", cost: 12 },
  { id: "dimensionalRift", name: "Dimensional Rift", icon: "🌀", desc: "Start eras with all zones", cost: 8 },
  { id: "soulHarvest", name: "Soul Harvest", icon: "👻", desc: "10% tree chops give +1 amber", cost: 20 },
  { id: "voidTouch", name: "Void Touch", icon: "🔮", desc: "Crit damage x5", cost: 18 },
];
export const W_NAMES = [
  "Bjorn",
  "Hilda",
  "Greta",
  "Olaf",
  "Freya",
  "Erik",
  "Sven",
  "Ingrid",
  "Lars",
  "Sigrid",
  "Astrid",
  "Ragnar",
  "Leif",
  "Thyra",
  "Harald",
  "Solveig",
  "Gunnar",
  "Runa",
  "Torsten",
  "Eira",
];
export const W_TITLES = [
  "the Swift",
  "the Strong",
  "Oakfeller",
  "Rootfinder",
  "Sharpaxe",
  "the Steady",
  "Barkstripper",
  "Treebane",
  "the Tireless",
  "Splinter",
];
export const ACHIEVEMENTS = [
  {
    id: "chop100",
    name: "Getting Started",
    desc: "Chop 100 trees",
    icon: "🌲",
    check: (g) => g.stats.treesChopped >= 100,
    bonus: "chop+1",
  },
  {
    id: "chop1000",
    name: "Lumberlord",
    desc: "Chop 1,000 trees",
    icon: "🪓",
    check: (g) => g.stats.treesChopped >= 1000,
    bonus: "chop+2",
  },
  {
    id: "chop10000",
    name: "Deforester",
    desc: "Chop 10,000 trees",
    icon: "🏆",
    check: (g) => g.stats.treesChopped >= 10000,
    bonus: "chop+5",
  },
  {
    id: "chop100k",
    name: "World Eater",
    desc: "Chop 100,000 trees",
    icon: "🌍",
    check: (g) => g.stats.treesChopped >= 100000,
    bonus: "chop+10",
  },
  {
    id: "chop500k",
    name: "Extinction Event",
    desc: "Chop 500K trees",
    icon: "💥",
    check: (g) => g.stats.treesChopped >= 500000,
    bonus: "chop+20",
  },
  {
    id: "chop1m",
    name: "Planet Destroyer",
    desc: "Chop 1M trees",
    icon: "🌒",
    check: (g) => g.stats.treesChopped >= 1000000,
    bonus: "chop+50",
  },
  {
    id: "logs1k",
    name: "Log Hoarder",
    desc: "Hold 1,000 logs",
    icon: "🪵",
    check: (g) => g.logs >= 1000,
    bonus: "yield+10%",
  },
  {
    id: "logs100k",
    name: "Lumber Mountain",
    desc: "Hold 100K logs",
    icon: "⛰️",
    check: (g) => g.logs >= 100000,
    bonus: "yield+15%",
  },
  {
    id: "logs1m",
    name: "Log Singularity",
    desc: "Hold 1M logs",
    icon: "🌀",
    check: (g) => g.logs >= 1000000,
    bonus: "yield+30%",
  },
  {
    id: "logs1b",
    name: "Infinite Logs",
    desc: "Hold 1B logs",
    icon: "♾️",
    check: (g) => g.logs >= 1000000000,
    bonus: "yield+50%",
  },
  {
    id: "gold10k",
    name: "Timber Baron",
    desc: "Earn 10K gold",
    icon: "🪙",
    check: (g) => g.stats.totalGold >= 10000,
    bonus: "gold+10%",
  },
  {
    id: "gold1m",
    name: "Tycoon",
    desc: "Earn 1M gold",
    icon: "💰",
    check: (g) => g.stats.totalGold >= 1000000,
    bonus: "gold+20%",
  },
  {
    id: "gold100m",
    name: "Monopolist",
    desc: "Earn 100M gold",
    icon: "💎",
    check: (g) => g.stats.totalGold >= 100000000,
    bonus: "gold+30%",
  },
  {
    id: "gold1b",
    name: "Billionaire",
    desc: "Earn 1B gold",
    icon: "🏦",
    check: (g) => g.stats.totalGold >= 1000000000,
    bonus: "gold+40%",
  },
  {
    id: "gold1t",
    name: "Trillionaire",
    desc: "Earn 1T gold",
    icon: "💸",
    check: (g) => g.stats.totalGold >= 1000000000000,
    bonus: "gold+50%",
  },
  {
    id: "workers5",
    name: "Foreman",
    desc: "Hire 5 workers",
    icon: "👷",
    check: (g) => g.workers.length >= 5,
    bonus: "worker+10%",
  },
  {
    id: "workers15",
    name: "Labor Union",
    desc: "Hire 15 workers",
    icon: "🏗️",
    check: (g) => g.workers.length >= 15,
    bonus: "worker+25%",
  },
  {
    id: "workers30",
    name: "Army of Axes",
    desc: "Hire 30 workers",
    icon: "⚔️",
    check: (g) => g.workers.length >= 30,
    bonus: "worker+40%",
  },
  {
    id: "workers50",
    name: "Mega Corp",
    desc: "Hire 50 workers",
    icon: "🏢",
    check: (g) => g.workers.length >= 50,
    bonus: "worker+50%",
  },
  {
    id: "workers100",
    name: "Corporation",
    desc: "Hire 100 workers",
    icon: "🏛️",
    check: (g) => g.workers.length >= 100,
    bonus: "worker+60%",
  },
  {
    id: "workers500",
    name: "Global Empire",
    desc: "Hire 500 workers",
    icon: "🌐",
    check: (g) => g.workers.length >= 500,
    bonus: "worker+100%",
  },
  {
    id: "season3",
    name: "Seasoned Vet",
    desc: "Reach Season 3",
    icon: "🍂",
    check: (g) => g.season >= 3,
    bonus: "prestige+1",
  },
  {
    id: "season10",
    name: "Ancient Forester",
    desc: "Reach Season 10",
    icon: "🌳",
    check: (g) => g.season >= 10,
    bonus: "prestige+2",
  },
  {
    id: "season25",
    name: "Eternal Autumn",
    desc: "Reach Season 25",
    icon: "🍁",
    check: (g) => g.season >= 25,
    bonus: "prestige+3",
  },
  {
    id: "season100",
    name: "Time Lord",
    desc: "Reach Season 100",
    icon: "⏳",
    check: (g) => g.season >= 100,
    bonus: "prestige+5",
  },
  { id: "era2", name: "New Era", desc: "Reach Era 2", icon: "⭐", check: (g) => g.era >= 2, bonus: "amber+1" },
  { id: "era5", name: "Timeless", desc: "Reach Era 5", icon: "🌟", check: (g) => g.era >= 5, bonus: "amber+2" },
  { id: "era10", name: "Epoch Herald", desc: "Reach Era 10", icon: "🔔", check: (g) => g.era >= 10, bonus: "amber+3" },
  {
    id: "era25",
    name: "Dimension Walker",
    desc: "Reach Era 25",
    icon: "🚪",
    check: (g) => g.era >= 25,
    bonus: "amber+5",
  },
  {
    id: "allZones",
    name: "Explorer",
    desc: "Unlock all zones",
    icon: "🗺️",
    check: (g) => g.unlockedZones.length >= 5,
    bonus: "yield+25%",
  },
  {
    id: "heartwood",
    name: "Heart Seeker",
    desc: "Chop a Heartwood",
    icon: "💜",
    check: (g) => g.stats.heartwoodChopped >= 1,
    bonus: "crit+5%",
  },
  {
    id: "worldtree",
    name: "World Shaker",
    desc: "Chop a Worldtree",
    icon: "🌍",
    check: (g) => g.stats.worldtreeChopped >= 1,
    bonus: "crit+10%",
  },
  {
    id: "golden50",
    name: "Gold Collector",
    desc: "Chop 50 golden trees",
    icon: "✨",
    check: (g) => g.stats.goldenChopped >= 50,
    bonus: "yield+20%",
  },
  {
    id: "ancient25",
    name: "Ancient Master",
    desc: "Chop 25 ancient trees",
    icon: "🏛️",
    check: (g) => g.stats.ancientChopped >= 25,
    bonus: "amber+2",
  },
  {
    id: "furn100",
    name: "Master Carpenter",
    desc: "Make 100 furniture",
    icon: "🪑",
    check: (g) => g.stats.furnitureMade >= 100,
    bonus: "furn+20%",
  },
  {
    id: "furn1000",
    name: "IKEA Founder",
    desc: "Make 1000 furniture",
    icon: "🏠",
    check: (g) => g.stats.furnitureMade >= 1000,
    bonus: "furn+40%",
  },
  {
    id: "furn10k",
    name: "Factory Owner",
    desc: "Make 10K furniture",
    icon: "🏭",
    check: (g) => g.stats.furnitureMade >= 10000,
    bonus: "furn+60%",
  },
  {
    id: "luxury100",
    name: "Luxury Dealer",
    desc: "Make 100 luxury goods",
    icon: "✨",
    check: (g) => g.stats.luxuryMade >= 100,
    bonus: "gold+15%",
  },
  {
    id: "luxury1k",
    name: "Luxury Magnate",
    desc: "Make 1K luxury",
    icon: "👑",
    check: (g) => g.stats.luxuryMade >= 1000,
    bonus: "gold+25%",
  },
  {
    id: "luxury10k",
    name: "Luxury Emperor",
    desc: "Make 10K luxury",
    icon: "🏰",
    check: (g) => g.stats.luxuryMade >= 10000,
    bonus: "gold+35%",
  },
  {
    id: "tech8",
    name: "Innovator",
    desc: "Research 8 techs",
    icon: "🔬",
    check: (g) => Object.values(g.techs).filter((v) => v).length >= 8,
    bonus: "all+5%",
  },
  {
    id: "techAll",
    name: "Omniscient",
    desc: "Research ALL techs",
    icon: "🧠",
    check: (g) => Object.values(g.techs).every((v) => v),
    bonus: "all+10%",
  },
  {
    id: "crits100",
    name: "Lucky Strike",
    desc: "Land 100 crits",
    icon: "⚡",
    check: (g) => g.stats.crits >= 100,
    bonus: "crit+5%",
  },
  {
    id: "crits1000",
    name: "Crit Machine",
    desc: "Land 1000 crits",
    icon: "🎯",
    check: (g) => g.stats.crits >= 1000,
    bonus: "crit+10%",
  },
  {
    id: "crits10k",
    name: "Crit God",
    desc: "Land 10K crits",
    icon: "⚡⚡",
    check: (g) => g.stats.crits >= 10000,
    bonus: "crit+15%",
  },
  {
    id: "boss10",
    name: "Boss Hunter",
    desc: "Defeat 10 bosses",
    icon: "💀",
    check: (g) => g.stats.bossesDefeated >= 10,
    bonus: "chop+15",
  },
  {
    id: "boss50",
    name: "Boss Slayer",
    desc: "Defeat 50 bosses",
    icon: "☠️",
    check: (g) => g.stats.bossesDefeated >= 50,
    bonus: "all+8%",
  },
  {
    id: "quests10",
    name: "Questmaster",
    desc: "Complete 10 quests",
    icon: "📜",
    check: (g) => g.stats.questsCompleted >= 10,
    bonus: "all+3%",
  },
  {
    id: "epoch2",
    name: "Transcendent",
    desc: "Reach Epoch 2",
    icon: "🌌",
    check: (g) => g.epoch >= 2,
    bonus: "all+10%",
  },
  {
    id: "epoch5",
    name: "Cosmic Being",
    desc: "Reach Epoch 5",
    icon: "🪐",
    check: (g) => g.epoch >= 5,
    bonus: "all+20%",
  },
  {
    id: "epoch10",
    name: "Reality Bender",
    desc: "Reach Epoch 10",
    icon: "🌀",
    check: (g) => g.epoch >= 10,
    bonus: "all+30%",
  },
];
export const QUEST_POOL = [
  {
    id: "chopPine50",
    name: "Pine Harvest",
    desc: "Chop 50 Pine trees",
    target: 50,
    stat: "pineChopped",
    reward: { type: "gold", amount: 500 },
  },
  {
    id: "chopOak30",
    name: "Oak Challenge",
    desc: "Chop 30 Oak trees",
    target: 30,
    stat: "oakChopped",
    reward: { type: "gold", amount: 1200 },
  },
  {
    id: "chopAny200",
    name: "Logging Frenzy",
    desc: "Chop 200 trees",
    target: 200,
    stat: "anyChopped",
    reward: { type: "gold", amount: 3000 },
  },
  {
    id: "earn5kGold",
    name: "Gold Rush",
    desc: "Earn 5,000 gold",
    target: 5000,
    stat: "goldEarned",
    reward: { type: "amber", amount: 1 },
  },
  {
    id: "make50Furn",
    name: "Furniture Drive",
    desc: "Make 50 furniture",
    target: 50,
    stat: "furnMade",
    reward: { type: "gold", amount: 8000 },
  },
  {
    id: "crit20",
    name: "Critical Mass",
    desc: "Land 20 critical hits",
    target: 20,
    stat: "critsLanded",
    reward: { type: "amber", amount: 1 },
  },
  {
    id: "sell500Logs",
    name: "Clearance Sale",
    desc: "Sell 500 logs",
    target: 500,
    stat: "logsSold",
    reward: { type: "gold", amount: 2000 },
  },
  {
    id: "chopHeart5",
    name: "Dark Heart",
    desc: "Chop 5 Heartwoods",
    target: 5,
    stat: "heartwoodChop",
    reward: { type: "amber", amount: 2 },
  },
  {
    id: "make20Char",
    name: "Charcoal Burner",
    desc: "Make 20 charcoal",
    target: 20,
    stat: "charMade",
    reward: { type: "gold", amount: 1500 },
  },
  {
    id: "chopIron20",
    name: "Iron Will",
    desc: "Chop 20 Ironwoods",
    target: 20,
    stat: "ironChopped",
    reward: { type: "gold", amount: 5000 },
  },
  {
    id: "luxury20",
    name: "Luxury Crafter",
    desc: "Make 20 luxury goods",
    target: 20,
    stat: "luxuryMade",
    reward: { type: "gold", amount: 15000 },
  },
];
export const EVENTS = [
  { name: "Wandering Merchant", icon: "🧳", desc: "A merchant offers premium prices!", duration: 30, effect: "goldx3" },
  {
    name: "Forest Fire",
    icon: "🔥",
    desc: "Some trees burned... but nutrients remain!",
    duration: 0,
    effect: "burnAndBoost",
  },
  {
    name: "Ancient Tree",
    icon: "🌳",
    desc: "An ancient tree appeared in the forest!",
    duration: 0,
    effect: "ancientTree",
  },
  { name: "Fairy Blessing", icon: "🧚", desc: "All yields doubled for 30 seconds!", duration: 30, effect: "yieldx2" },
  {
    name: "Lucky Wind",
    icon: "🍃",
    desc: "Critical hits guaranteed for 20 seconds!",
    duration: 20,
    effect: "critBoost",
  },
  { name: "Merchant Caravan", icon: "🐪", desc: "Sell prices tripled for 25 seconds!", duration: 25, effect: "goldx3" },
];
export const ASCENSION_TREE = [
  {
    id: "headStart",
    name: "Head Start",
    icon: "🚀",
    desc: "Start seasons with 500 gold",
    cost: 3,
    branch: "speed",
    row: 0,
    req: [],
  },
  {
    id: "keenEdge",
    name: "Keen Edge",
    icon: "🗡️",
    desc: "+5 chop power",
    cost: 2,
    branch: "speed",
    row: 1,
    req: ["headStart"],
  },
  {
    id: "bornLeader",
    name: "Born Leader",
    icon: "👑",
    desc: "Keep 1 extra worker per season reset",
    cost: 5,
    branch: "yield",
    row: 0,
    req: [],
  },
  {
    id: "quickStudy",
    name: "Quick Study",
    icon: "📚",
    desc: "Tech costs -10%",
    cost: 4,
    branch: "yield",
    row: 1,
    req: ["bornLeader"],
  },
  {
    id: "natureBond",
    name: "Nature's Bond",
    icon: "🌿",
    desc: "Regrow speed +20%",
    cost: 3,
    branch: "automation",
    row: 0,
    req: [],
  },
  {
    id: "goldenTouch",
    name: "Golden Touch",
    icon: "✨",
    desc: "Gold income +15%",
    cost: 4,
    branch: "automation",
    row: 1,
    req: ["natureBond"],
  },
  {
    id: "deepPockets",
    name: "Deep Pockets",
    icon: "💰",
    desc: "Start with 1 free sawmill level",
    cost: 6,
    branch: "speed",
    row: 2,
    req: ["keenEdge"],
  },
  {
    id: "luckCharm",
    name: "Luck Charm",
    icon: "🍀",
    desc: "+3% crit chance",
    cost: 5,
    branch: "yield",
    row: 2,
    req: ["quickStudy"],
  },
  {
    id: "zoneMemory",
    name: "Zone Memory",
    icon: "🗺️",
    desc: "Keep 1 unlocked zone per season",
    cost: 8,
    branch: "automation",
    row: 2,
    req: ["goldenTouch"],
  },
  {
    id: "amberMagnet",
    name: "Amber Magnet",
    icon: "🔶",
    desc: "+1 bonus amber per season",
    cost: 10,
    branch: "speed",
    row: 3,
    req: ["deepPockets"],
  },
  {
    id: "goldenMutation",
    name: "Golden Mutation",
    icon: "💛",
    desc: "Golden trees appear 2x as often",
    cost: 7,
    branch: "yield",
    row: 3,
    req: ["luckCharm"],
  },
  {
    id: "ancientHunter",
    name: "Ancient Hunter",
    icon: "👻",
    desc: "Ancient trees drop +1 amber",
    cost: 8,
    branch: "automation",
    row: 3,
    req: ["zoneMemory"],
  },
];
export const CONTRACTS_POOL = [
  {
    id: "logs-5000",
    name: "Big Log Order",
    desc: "Deliver 5000 logs",
    target: 5000,
    stat: "totalLogs",
    reward: { type: "gold", amount: 50000 },
    timeLimit: 600,
  },
  {
    id: "planks-2000",
    name: "Lumber Mill",
    desc: "Process 2000 planks",
    target: 2000,
    stat: "planksProduced",
    reward: { type: "amber", amount: 3 },
    timeLimit: 600,
  },
  {
    id: "charcoal-500",
    name: "Charcoal Supply",
    desc: "Burn 500 charcoal",
    target: 500,
    stat: "charcoalMade",
    reward: { type: "gold", amount: 35000 },
    timeLimit: 600,
  },
  {
    id: "ironwood-300",
    name: "Ironwood Specialist",
    desc: "Chop 300 Ironwood",
    target: 300,
    stat: "ironwoodChopped",
    reward: { type: "gold", amount: 80000 },
    timeLimit: 900,
  },
  {
    id: "gold-200k",
    name: "Gold Rush",
    desc: "Earn 200000 gold",
    target: 200000,
    stat: "goldEarned",
    reward: { type: "amber", amount: 5 },
    timeLimit: 900,
  },
  {
    id: "trees-500",
    name: "Logging Expert",
    desc: "Chop 500 trees total",
    target: 500,
    stat: "treesChopped",
    reward: { type: "gold", amount: 75000 },
    timeLimit: 800,
  },
  {
    id: "furniture-100",
    name: "Furniture Dealer",
    desc: "Craft 100 furniture",
    target: 100,
    stat: "furnMade",
    reward: { type: "gold", amount: 60000 },
    timeLimit: 900,
  },
  {
    id: "luxury-50",
    name: "Luxury Trade",
    desc: "Make 50 luxury goods",
    target: 50,
    stat: "luxuryMade",
    reward: { type: "amber", amount: 4 },
    timeLimit: 900,
  },
];
export const ZONE_SPECIALTIES = [
  { name: "Resin", icon: "🫙" },
  { name: "Mushrooms", icon: "🍄" },
  { name: "Ore", icon: "⛏️" },
  { name: "Crystals", icon: "💎" },
  { name: "Frost Essence", icon: "❄️" },
];
export const DEMAND_RESOURCES = ["logs", "planks", "charcoal", "furniture", "luxury"];
export const BOSS_TYPES = [
  { name: "Elder Oak", tier: 1, hpMul: 50, reward: { gold: 5000, amber: 2 } },
  { name: "Iron Titan", tier: 3, hpMul: 80, reward: { gold: 20000, amber: 5 } },
  { name: "World Sentinel", tier: 5, hpMul: 120, reward: { gold: 100000, amber: 10 } },
];
export const AXE_COSMETICS = [
  { id: "default", name: "Wood Axe", era: 1, color: "#b08850", spark: "#8B6914" },
  { id: "silver", name: "Silver Axe", era: 2, color: "#d8dde6", spark: "#c0c8d8" },
  { id: "gold", name: "Gold Axe", era: 3, color: "#ffcf40", spark: "#ffd700" },
  { id: "diamond", name: "Diamond Axe", era: 5, color: "#8ff0ff", spark: "#aef6ff" },
];
